version: "3.8"  # Schema version

services:
  app:
    image: node:12
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: pasword
      MYSQL_DB: db-name
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db-name
volumes:
  todo-mysql-data:



# services are the containers we definded in the below way previously, just  a different layout

###### TODO APP
# docker run -dp 3000:3000 \
#   -w /app -v "$(pwd):/app" \
#   --network todo-app \
#   -e MYSQL_HOST=mysql \
#   -e MYSQL_USER=root \
#   -e MYSQL_PASSWORD=secret \
#   -e MYSQL_DB=todos \
#   node:12-alpine \
#   sh -c "yarn install && yarn run dev"

#### MYSQL DB
# docker run -d \
#   --network todo-app --network-alias mysql \
#   -v todo-mysql-data:/var/lib/mysql \
#   -e MYSQL_ROOT_PASSWORD=secret \
#   -e MYSQL_DATABASE=todos \
#   mysql:5.7